Repository maelgangloff/scolengo-api, pull requests merged in 2023-04, with the labels that each got.

#2 Ajout des actualités de l'établissement
  README.md
  src/index.ts
  src/models/Attachment.ts
  src/models/SchoolInfo.ts
Labels: enhancement

#8 Implémentation agenda et lessons
  README.md
  src/index.ts
  src/models/Agenda/Agenda.ts
  src/models/Agenda/Lesson.ts
  src/models/App/User.ts
  src/models/Homework/HomeworkAssignment.ts
  src/models/School/Attachment.ts
  src/models/School/SchoolInfo.ts
  tests/Agenda.test.ts
  tests/Homework.test.ts
  tests/Lesson.test.ts
  tests/SchoolInfo.test.ts
  tests/SearchSchool.test.ts
Labels: enhancement

#11 Ajout de la documentation pour le travail à faire
  README.md
  src/index.ts
Labels: documentation

#22 fix (messagerie): recepients are contacts
  src/models/Messagerie/Communication.ts
Labels: bug
